AWSTemplateFormatVersion: 2010-09-09
Description: This is The Belt CloudFormation

Parameters:
  AmiId:
    Type: String
    Description: Amazon Machine Image ID (Amazon Linux 2)
    Default: ami-0cff7528ff583bf9a

  InstanceType:
    Type: String
    Description: Allowed Instance Types
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium

  SSHIp:
    Type: String
    Description: The IP address range that can be used to SSH to the EC2 instances
    Default: 0.0.0.0/0
    MinLength: 9
    MaxLength: 18
    AllowedPattern: (\d{1,3}).(\d{1,3}).(\d{1,3}).(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  # Cretate an EC2 Instance
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: Shaikh-cloudformation

  # Create a Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHIp
Outputs:
  AzName:
    Description: The Availability Zone of the EC2 Instance
    Value: !GetAtt Ec2Instance.AvailabilityZone
  Ec2InstancePublicDns:
    Description: This gives the public Dns
    Value: !GetAtt Ec2Instance.PublicDnsName
  Ec2InstancePublicIpAddress:
    Description: This gives the public ip address
    Value: !GetAtt Ec2Instance.PublicIp
